CREATE DATABASE SILVERDRAGON;
USE SILVERDRAGON;
CREATE TABLE PROJECTS(
	PROJECT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PROJECT_CODE VARCHAR(100) NOT NULL,
	PROJECT_DESCRIPTION TEXT NOT NULL,
	PROJECT_SITE TEXT NOT NULL,
	PROJECT_START_DATE DATE	NOT NULL,
	CONTRACT_ID INT NOT NULL
);

CREATE TABLE CONTRACTS(
	CONTRACT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PROJECT_ID INT NOT NULL,
	CONTRACT_BUDGET DOUBLE(18,2) NOT NULL,
	CONTRACT_CALENDAR_DAYS DOUBLE(18,2) NOT NULL
);

CREATE TABLE INVENTORY(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SKU VARCHAR(255) NOT NULL,
	ITEM_DESCRIPTION VARCHAR(255) NOT NULL,
	ITEM_UNIT_COST DOUBLE(18,2) NOT NULL,
	ITEM_TYPE_ID INT NOT NULL,
	LOCATION_ID INT NOT NULL,
	STOCK DOUBLE(18,2) NOT NULL
);

CREATE TABLE ITEM_TYPE(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ITEM_TYPE_DESCRIPTION VARCHAR(255)
);

CREATE TABLE LOCATION(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ITEM_LOCATION TEXT NOT NULL
);

CREATE TABLE ACCOMPLISHMENT(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ACCOMPLISHMENT_TYPE INT NOT NULL, --0 FOR PLANNED 1 FOR ACTUAL
	ACCOMPLISHMENT_DESCRIPTION TEXT NOT NULL
);

CREATE TABLE ACC_PROJ_LINK(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PROJECT_ID INT NOT NULL,
	ACCOMPLISHMENT_ID INT NOT NULL
);