CREATE DATABASE IF NOT EXISTS MIRASOLTIRESUPPLY;
USE MIRASOLTIRESUPPLY;

CREATE TABLE USERS(
	USER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USER_FNAME VARCHAR(255) NOT NULL,
	USER_LNAME VARCHAR(255) NOT NULL,
	USER_M_INITIAL CHAR NOT NULL,
	USER_EMAIL VARCHAR(255) NOT NULL,
	USER_PASSWORD VARCHAR(255) NOT NULL,
	USER_ADDRESS TEXT NOT NULL,
	USER_GENDER INT NOT NULL,
	USER_CONTACT_NO VARCHAR(255) NOT NULL,
	USER_TYPE_ID INT NOT NULL
);

CREATE TABLE TRANSACTION(
	TRANSACTION_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT NOT NULL,
	TRANSACTION_TYPE INT NOT NULL,
	TEANSACTION_DATE TIMESTAMP NOT NULL,
	TRANSCTION_MOP INT NOT NULL, 
	TRANSACTION_STATUS INT NOT NULL
);

CREATE TABLE TRANSACTION_DETAIL(
	TD_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TRANSACTION_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
	TD_QTY INT NOT NULL,
	TD_TOTAL DOUBLE(18,2) NOT NULL
);

CREATE TABLE PRODUCT(
	PRODUCT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PRODUCT_TYPE INT NOT NULL,
	PRODUCT_COST_PER_UNIT DOUBLE(18,2) NOT NULL,
	PRODUCT_STOCK INT NOT NULL
);

CREATE TABLE TIRE(
	TIRE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PRODUCT_ID INT NOT NULL,
	TIRE_RIM VARCHAR(255) NOT NULL,
	TIRE_SIZE DOUBLE(8,2) NOT NULL,
	TIRE_LI_SS DOUBLE(8,2) NOT NULL,
	TIRE_BRAND VARCHAR(255) NOT NULL,
	TIRE_DESIGN VARCHAR(255) NOT NULL,
	TIRE_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE WHEEL(
	WHEEL_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PRODUCT_ID INT NOT NULL,
	WHEEL_RIM VARCHAR(255) NOT NULL,
	WHEEL_CODE VARCHAR(255) NOT NULL,
	WHEEL_COLOR VARCHAR(255) NOT NULL,
	WHEEL_HOLES INT NOT NULL
);

CREATE TABLE BATTERY(
	BATTERY_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PRODUCT_ID INT NOT NULL,
	BATTERY_TYPE INT NOT NULL,
	BATTERY_PLATES INT NOT NULL,
	BATTERY_CLASSIC_HR VARCHAR(255) NOT NULL,
	BATTERY_TRUCKMASTER VARCHAR(255) NOT NULL,
	BATTERY_SUPER_PREM VARCHAR(255) NOT NULL
);

CREATE TABLE RESCUE(
	RESCUE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TRANSACTION_ID INT NOT NULL,
	RESCUE_NAME VARCHAR(255) NOT NULL,
	RESCUE_CSR_NO INT NOT NULL,
	RESCUE_DATE TIMESTAMP NOT NULL,
	RESCUE_X_COORDINATE DOUBLE(8,8) NOT NULL,
	RESCUE_Y_COORDINATE DOUBLE(8,8) NOT NULL
);

CREATE TABLE COD(
	COD_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TRANSACTION_ID INT NOT NULL,
	COD_CAREOF VARCHAR(255) NOT NULL,
	COD_STATUS INT NOT NULL,
	COD_DATE_RECEIVED TIMESTAMP NOT NULL,
	COD_DATE_ISSUED TIMESTAMP NOT NULL
);

CREATE TABLE CREDIT_CARD(
	CC_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TRANSACTION_ID INT NOT NULL,
	CC_DATE_RECEIVED TIMESTAMP NOT NULL,
	CC_CARD_NO INT NOT NULL,
	CC_DATE_ISSUED TIMESTAMP NOT NULL,
	CC_BANK VARCHAR(255) NOT NULL,
	CC_NAME_IN_CARD VARCHAR(255) NOT NULL,
	CC_EXPIRATION_DATE TIMESTAMP NOT NULL,
	CC_CARD_TYPE INT NOT NULL,
	CC_SECURITY_CODE VARCHAR(255) NOT NULL,
	CC_BILLING_ADDRESS TEXT NOT NULL
);

CREATE TABLE CHEQUE(
	CHEQUE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TRANSACTION_ID INT NOT NULL,
	CHEQUE_DATE_ISSUED TIMESTAMP NOT NULL,
	CHEQUE_BANK VARCHAR(255) NOT NULL,
	CHEQUE_NUMBER VARCHAR(255) NOT NULL,
	CHEQUE_DATE_RECEIVED TIMESTAMP NOT NULL
);

CREATE TABLE COMMENT(
	COMMENT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	COMMENT_NAME VARCHAR(255) NOT NULL,
	COMMENT_EMAIL VARCHAR(255) NOT NULL,
	COMMENT_MESSAGE LONGTEXT NOT NULL
)